def decrypto(frase):
    tradutor = ''
    for letra in frase:
      if letra in '✺': tradutor = tradutor + 'A'
      elif letra in 'Ⅸ': tradutor = tradutor + 'B'
      elif letra in 'ⅷ': tradutor = tradutor + 'C'
      elif letra in '⇶': tradutor = tradutor + 'D'
      elif letra in '⋉': tradutor = tradutor + 'E'
      elif letra in '⊼': tradutor = tradutor + 'F'
      elif letra in '⌘': tradutor = tradutor + 'G'
      elif letra in '⊇': tradutor = tradutor + 'H'
      elif letra in '⟱': tradutor = tradutor + 'I'
      elif letra in 'ℒ': tradutor = tradutor + 'J'
      elif letra in '♰': tradutor = tradutor + 'L'
      elif letra in '✠': tradutor = tradutor + 'M'
      elif letra in '⥾': tradutor = tradutor + 'N'
      elif letra in '⥵': tradutor = tradutor + 'O'
      elif letra in '℺': tradutor = tradutor + 'P'
      elif letra in '⅂': tradutor = tradutor + 'Q'
      elif letra in 'Ƹ': tradutor = tradutor + 'R'
      elif letra in 'ƺ': tradutor = tradutor + 'S'
      elif letra in 'ȸ': tradutor = tradutor + 'T'
      elif letra in 'φ': tradutor = tradutor + 'U'
      elif letra in 'Ϣ': tradutor = tradutor + 'V'
      elif letra in 'λ': tradutor = tradutor + 'X'
      elif letra in 'ȣ': tradutor = tradutor + 'Z'
      elif letra in 'Ш': tradutor = tradutor + 'W'
      elif letra in 'ɀ': tradutor = tradutor + 'Y'
      elif letra in 'ƕ': tradutor = tradutor + 'K'
      elif letra in 'ɱ': tradutor = tradutor + 'a'
      elif letra in '#': tradutor = tradutor + 'b'
      elif letra in '$': tradutor = tradutor + 'c'
      elif letra in '&': tradutor = tradutor + 'd'
      elif letra in 'Ѿ': tradutor = tradutor + 'e'
      elif letra in 'ȣ': tradutor = tradutor + 'f'
      elif letra in '': tradutor = tradutor + 'g'
      elif letra in '‡': tradutor = tradutor + 'h'
      elif letra in 'ʝ': tradutor = tradutor + 'i'
      elif letra in 'Ȼ': tradutor = tradutor + 'j'
      elif letra in 'Œ': tradutor = tradutor + 'l'
      elif letra in '⎲': tradutor = tradutor + 'm'
      elif letra in '⎨': tradutor = tradutor + 'n'
      elif letra in '⊪': tradutor = tradutor + 'o'
      elif letra in '⋣': tradutor = tradutor + 'p'
      elif letra in '⋔': tradutor = tradutor + 'q'
      elif letra in '╳': tradutor = tradutor + 'r'
      elif letra in '╪': tradutor = tradutor + 's'
      elif letra in '┋': tradutor = tradutor + 't'
      elif letra in '⋲': tradutor = tradutor + 'u'
      elif letra in '≴': tradutor = tradutor + 'v'
      elif letra in '༒': tradutor = tradutor + 'x'
      elif letra in '⨁': tradutor = tradutor + 'z'
      elif letra in '⅁': tradutor = tradutor + 'w'
      elif letra in '♐': tradutor = tradutor + 'y'
      elif letra in '⥢': tradutor = tradutor + 'k'

      else:
        tradutor = tradutor + letra
    return tradutor
while True:
      print(decrypto(input("Digite o codigo a ser Decryptado: ")))


    
