def crypto(frase):
    tradutor = ''
    for letra in frase:
      if letra in "A": tradutor = tradutor + "✺"
      elif letra in 'B': tradutor = tradutor + 'Ⅸ'
      elif letra in 'C': tradutor = tradutor + 'ⅷ'
      elif letra in 'D': tradutor = tradutor + '⇶'
      elif letra in 'E': tradutor = tradutor + '⋉'
      elif letra in 'F': tradutor = tradutor + '⊼'
      elif letra in 'G': tradutor = tradutor + '⌘'
      elif letra in 'H': tradutor = tradutor + '⊇'
      elif letra in 'I': tradutor = tradutor + '⟱'
      elif letra in 'J': tradutor = tradutor + 'ℒ'
      elif letra in 'L': tradutor = tradutor + '♰'
      elif letra in 'M': tradutor = tradutor + '✠.'
      elif letra in 'N': tradutor = tradutor + '⥾'
      elif letra in 'O': tradutor = tradutor + '⥵'
      elif letra in 'P': tradutor = tradutor + '℺'
      elif letra in 'Q': tradutor = tradutor + '⅂'
      elif letra in 'R': tradutor = tradutor + 'Ƹ'
      elif letra in 'S': tradutor = tradutor + 'ƺ'
      elif letra in 'T': tradutor = tradutor + 'ȸ'
      elif letra in 'U': tradutor = tradutor + 'φ'
      elif letra in 'V': tradutor = tradutor + 'Ϣ'
      elif letra in 'X': tradutor = tradutor + 'λ'
      elif letra in 'Z': tradutor = tradutor + 'ȣ'
      elif letra in 'W': tradutor = tradutor + 'Ш'
      elif letra in 'Y': tradutor = tradutor + 'ɀ'
      elif letra in 'K': tradutor = tradutor + 'ƕ'
      elif letra in "a": tradutor = tradutor + "ɱ"
      elif letra in 'b': tradutor = tradutor + '#'
      elif letra in 'c': tradutor = tradutor + '$'
      elif letra in 'd': tradutor = tradutor + '&'
      elif letra in 'e': tradutor = tradutor + 'Ѿ'
      elif letra in 'f': tradutor = tradutor + 'ȣ'
      elif letra in 'g': tradutor = tradutor + ''
      elif letra in 'h': tradutor = tradutor + '‡'
      elif letra in 'i': tradutor = tradutor + 'ʝ'
      elif letra in 'j': tradutor = tradutor + 'Ȼ'
      elif letra in 'l': tradutor = tradutor + 'Œ'
      elif letra in 'm': tradutor = tradutor + '⎲'
      elif letra in 'n': tradutor = tradutor + '⎨'
      elif letra in 'o': tradutor = tradutor + '⊪'
      elif letra in 'p': tradutor = tradutor + '⋣'
      elif letra in 'q': tradutor = tradutor + '⋔'
      elif letra in 'r': tradutor = tradutor + '╳'
      elif letra in 's': tradutor = tradutor + '╪ '
      elif letra in 't': tradutor = tradutor + '┋'
      elif letra in 'u': tradutor = tradutor + '⋲'
      elif letra in 'v': tradutor = tradutor + '≴'
      elif letra in 'x': tradutor = tradutor + '༒ '
      elif letra in 'z': tradutor = tradutor + '⨁'
      elif letra in 'w': tradutor = tradutor + '⅁'
      elif letra in 'y': tradutor = tradutor + '♐'
      elif letra in 'k': tradutor = tradutor + '⥢ '

      else: tradutor = tradutor + letra
    return tradutor
while True:
      print(crypto(input("Digite a frase desejada: ")))
